# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: vue.js Korea
email: pcjpcj2@gmail.com
description: vue.js에 대한 내용을 다룹니다
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vuejs-kr.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  vuejs-kr
paginate: 5

gems: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
highlighter: rouge
kramdown.syntax_highlighter_opts.block.line_numbers: true
